# Generated by Django 4.2.4 on 2023-08-21 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_rename_is_completed_todo_date_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='date_completed',
            field=models.BooleanField(default=True),
        ),
    ]
